### ISSUE TITLE
你好，请问可以看一下你的bot么

### ISSUE THREAD

**Issue by 800catties** [daycold1000/miaoshop#1]
我自己小群搭了个bot玩想用一下你的插件请问可以么，看着应该是还有其他插件的，请问可以用一下你的其他插件么（不知道怎么表达希望你能看懂我的意思）

**Comment by daycold1000** [comment]
懂的，不过先不要急，相关的插件玩法会相继上传，但注意，我的bot已经在11月2日停止服务了，插件是不会再继续更新的

**Comment by daycold1000** [comment]
哦注意，你看到了商店内有钓鱼杆，但那个玩法我并在停止服务前并没有编写，因此并没有钓鱼功能（如果有能力可以试着自己写？）

**Comment by daycold1000** [comment]
> 我自己小群搭了个bot玩想用一下你的插件请问可以么，看着应该是还有其他插件的，请问可以用一下你的其他插件么（不知道怎么表达希望你能看懂我的意思）



> 我自己小群搭了个bot玩想用一下你的插件请问可以么，看着应该是还有其他插件的，请问可以用一下你的其他插件么（不知道怎么表达希望你能看懂我的意思）

如果无法等到我的上传的话，你可以发送email给我：miao-time@foxmail.com，我会把剩下没整理好的打包给你

**Comment by daycold1000** [comment]
您好！本插件发现了bug【严重，干扰功能运行】并修复完成，新的代码已经上传，请重新拉取并覆盖，新增一个指令，详情见readme！
