### ISSUE TITLE
到了5点商店不补货

### ISSUE THREAD

**Issue by 495luke** [daycold1000/miaoshop#2]
看了日志也没什么报错文案，也不知道什么bug造成的。能否添加一个手动补货的指令

**Comment by daycold1000** [comment]
问题已复现，需求收到，正在修改中，如果此条issues关闭即为修改完成，可以重新拉取代码覆盖

**Comment by 495luke** [comment]
辛苦大佬了

**Comment by daycold1000** [comment]
问题：在每日5点补货时，因一个低级错误（真的低级错误呜呜呜，当时上传代码的时候迷糊快睡着了没注意倒）导致补货时报错ERROR: <class 'UnboundLocalError'> occured when doing scheduled job clock.
UnboundLocalError: local variable 'shopnew' referenced before assignment

结果：现问题已修复，请您重新拉取代码并覆盖。

建议：增加一个手动补货的指令

结果：建议采纳，新增指令“强制补货”，详细情况见readme内容

2022-12-14 22:29:50
